mutation AddNewLoanApplication($loanTypeId: UUID!, $userId: UUID!, $applicationDate: Date!, $applicationId: String!, $requestedAmount: Float!, $status: String!) @auth(level: USER) {
  loanApplication_insert(data: {loanTypeId: $loanTypeId, userId: $userId, applicationDate: $applicationDate, applicationId: $applicationId, requestedAmount: $requestedAmount, status: $status})
}

query GetLoanApplicationsForUser($userId: UUID!) @auth(level: USER) {
  loanApplications(where: {userId: {eq: $userId}}) {
    id
    applicationId
    status
    requestedAmount
  }
}

mutation UpdateLoanApplicationStatus($id: UUID!, $status: String!) @auth(level: USER) {
  loanApplication_update(key: {id: $id}, data: {status: $status})
}

query ListLoanTypes @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  loanTypes {
    id
    name
    description
    maxAmount
    interestRateRange
  }
}